//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Micro_Finance.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=THEARA_PC\\SQLSERVER;User ID=sa;Password=12345")]
        public string ConnectionString {
            get {
                return ((string)(this["ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=THEARA_PC\\SQLSERVER;Initial Catalog=dbMicro_Finance;User ID=sa;Passwo" +
            "rd=12345")]
        public string dbMicro_FinanceConnectionString {
            get {
                return ((string)(this["dbMicro_FinanceConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PC;Initial Catalog=dbMicro_Finance;User ID=sa;Password=master123")]
        public string dbMicro_FinanceConnectionString1 {
            get {
                return ((string)(this["dbMicro_FinanceConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PC;Initial Catalog=dbMicro_Finance;Integrated Security=True")]
        public string dbMicro_FinanceConnectionString2 {
            get {
                return ((string)(this["dbMicro_FinanceConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ASUS\\SQLSERVER;Initial Catalog=dbMicro_Finance;Persist Security Info=" +
            "True;User ID=sa;Password=12345")]
        public string dbMicro_FinanceConnectionString3 {
            get {
                return ((string)(this["dbMicro_FinanceConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=AEC-PC\\SQLSERVER;Initial Catalog=dbMicro_Finance;User ID=sa;Password=" +
            "12345")]
        public string dbMicro_FinanceConnectionString4 {
            get {
                return ((string)(this["dbMicro_FinanceConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PC001;Initial Catalog=dbMicro_Finance;Persist Security Info=True;User" +
            " ID=sa;Password=12345")]
        public string dbMicro_FinanceConnectionString5 {
            get {
                return ((string)(this["dbMicro_FinanceConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=THEARA;Initial Catalog=dbMicro_Finance;Persist Security Info=True;Use" +
            "r ID=sa;Password=12345")]
        public string dbMicro_FinanceConnectionString6 {
            get {
                return ((string)(this["dbMicro_FinanceConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=THEARA-PC\\THEARA;Initial Catalog=dbMicro_Finance;Persist Security Inf" +
            "o=True;User ID=sa;Password=12345")]
        public string dbMicro_FinanceConnectionString7 {
            get {
                return ((string)(this["dbMicro_FinanceConnectionString7"]));
            }
        }
    }
}
